Frontend:
  impl: GEM5
  clock_ratio: 1
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: HBM2
    org:
      preset: HBM2_2Gb
      channel: 8
      rank: 1
    timing:
      preset: HBM2_2Gbps 

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: ClosedRowPolicy
      cap: 4
    plugins:

  AddrMapper:
    impl: RoBaRaCoCh
